services:
  deepseek-harness:
    build: https://github.com/AngelGarzaDev/deepseek-harness-docker.git
    image: deepseek-harness
    container_name: deepseek-harness
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      # Maps host directory to the root home directory of the container
      - dsh-data:/root/.dsh

volumes:
  dsh-data:
